### PR TITLE
Add methods for options

### PR DESCRIPTION
**Pull request by tacyan**
lib/openstack/core_ext/to_query.rb = ↓
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/core_ext/object/to_query.rb

OpenStack.paginate ⇛ to_query

pry

```ruby
require "openstack"
=> true

{:limit => 2, :offset => 3, :name => "MyServer", :status => "ACTIVE"}.to_query
=> "limit=2&name=MyServer&offset=3&status=ACTIVE"

OpenStack.paginate({:limit => 2, :offset => 3, :name => "MyServer", :status => "ACTIVE"})
=> "limit=2&offset=3"
```

change methods

lib/openstack/compute/connection.rb

list_servers
list_servers_detail
list_images
list_flavors

### CODE REVIEW

**Comment by f0086** [comment]
Thanks!
Can you please fix the indentation of the code and add basic tests for your changes?

**Comment by tacyan** [comment]
Thanks for comment.
please wait add basic tests.

**Comment by tacyan** [comment]
I added unit test for options.

**Comment by f0086** [comment]
Thanks!

**Comment by tacyan** [comment]
Thanks!

**Pull request merged**
