### PR TITLE
Add identity service support

### PR DESCRIPTION
**Pull request by Qwertyn**
Added service on manage tenants and users
We need your help to tests earned

### CODE REVIEW

**Comment by f0086** [comment]
Tests are failing :cry: 
If you fix the test, I will merge it into ```next```

**Comment by Qwertyn** [comment]
fixed test

**Comment by james-poore** [comment]
@Qwertyn I have run into some issues using this.  Whenever I call list_tenants it works fine and uses the appropriate endpoint 'http://{my_openstack}/keystone_admin/v2.0', but whenever I call list_users or list_roles I get a 404 error. I discovered that for list_users and list_roles it uses a different endpoint 'http://{my_openstack}/keystone/v2.0'.  For tenants it's using the adminURL of the identity service endpoints and for users and roles it's using the publicURL.

**Comment by Qwertyn** [comment]
Yes, that is right. When using `endpoint_type: adminURL` access to all lists: list_tenants, list_users, list_roles.
When using `endpoint_type: publicURL` available not all tenants and does not accessible lists of users and roles (response code 404)

**Pull request merged**
